# Generated by Django 5.1.3 on 2024-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Bootstrap icon class (e.g., bi-tree)', max_length=50)),
                ('image', models.ImageField(upload_to='benefits/')),
            ],
        ),
    ]
